const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm'),cp=require('node:child_process');
const P=require('../blum-prompts');const root=path.resolve(__dirname,'../..');const els={};
function el(id){return els[id]||(els[id]={value:({run:'prompt-check',model:'claude-haiku-4-5',n:'1'})[id]||'',checked:true,hidden:true,appendChild(){},addEventListener(){}})}
const ctx={BlumPrompts:P,document:{querySelector:s=>el(s.slice(1)),getElementById:el,querySelectorAll:()=>[],createElement:()=>({appendChild(){},click(){}})},URLSearchParams,location:{search:''},Date,Set,JSON,alert:msg=>{throw Error(msg)}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'tools/blum-pilot-panel.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1],ctx);
const m=JSON.parse(vm.runInContext('JSON.stringify(build())',ctx));assert(m.cells.some(c=>c.cell==='C'&&c.kind==='cold'));
const canonical=JSON.parse(fs.readFileSync(path.join(root,'experiments/EXP-003-the-sixth-question/pilot-control-panel-koan-hfas.json')));assert.equal(m.step1.L,canonical.step1.AS);
assert(P.head(m,'L').includes('Step 2:'));assert(P.head(m,'L').includes('Step 3:'));assert(P.cold(m,'E01').includes(m.keys.credence));assert(els.promptPreview.innerHTML.includes('Think it through however you like'));assert(!els.promptPreview.innerHTML.includes('undefined'));
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'blum-prompts-'));const file=path.join(dir,'manifest.json');fs.writeFileSync(file,JSON.stringify(m));const r=cp.spawnSync(process.execPath,['tools/blum-pilot-runner.js','--manifest',file,'--out',path.join(dir,'output')],{cwd:root,encoding:'utf8',maxBuffer:5e6});assert.equal(r.status,0,r.stderr);for(const c of m.cells)for(const p of P.prompts(m,c))assert(r.stdout.includes(p.text),c.cell+' '+p.label+' must match full collector prompt');
assert(r.stdout.includes('cell C (cold)'));assert(r.stdout.includes('distinctive syntactical register (ALLCAPS'));
const exact={...m,exact_turns:{Q1:'Exact full first prompt'},cells:[]};assert.equal(P.prompts(exact,{kind:'trunk',schema:'J',slate:['Q1']})[0].text,'Exact full first prompt');assert.equal(P.prompts({...m,items:{X:{exact_prompt:'Exact full battery prompt'}}},{kind:'branch',schema:null})[0].text,'Exact full battery prompt');
console.log('Full schema, continuation, dropped-schema and fresh-control previews match collector dry runs without truncation.');
